### ISSUE TITLE
Failed to initialise MimoStandUp environment

### ISSUE THREAD

**Issue by dodio12138** [Domattee/MIMo#19]
I think this is because ``**kwargs`` are missing from ``MIMoStandupEnv.__init__()`` and ``MIMoStandupEnv.super.__init__()`` in the ``standup.py`` script ( Path: /mimoEnv/envs/standup.py ). After adding it, It can run.

**Comment by Domattee** [comment]
Thanks for pointing this out, fixed! 
Just out of curiosity, could you tell us the stack trace and what command lead to this issue? Both benchmarking and demo scripts run (for us anyway) even without the kwarg passthrough, it'd be interesting to see what argument and from what module/wrapper was causing problems.

**Comment by dodio12138** [comment]
Of course, I use  ```env = gym.make("MIMoStandup-v0", render_mode = 'human')```  to import the environment, and the Traceback displayed is: 
```
Traceback (most recent call last):
  File "/home/dodio/Desktop/BABY/myScene.py", line 11, in <module>
    env = gym.make("MIMoStandup-v0", render_mode = 'human')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dodio/anaconda3/envs/BABY/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 813, in make
    raise e
  File "/home/dodio/anaconda3/envs/BABY/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 801, in make
    env = env_creator(**env_spec_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MIMoStandupEnv.__init__() got an unexpected keyword argument 'render_mode' 
```

My running env:
ubuntu 22.04.3 LTS
python 3.11.5
mujoco 2.3.7
gymnasium 0.28.1

**Comment by Domattee** [comment]
Thanks!
Turns out I really need to write a test suite, I would've thought illustrations.py or benchmark.py would use this parameter.
