### ISSUE TITLE
Unexpected behavior when compensating gravity

### ISSUE THREAD

**Issue by marcogfedozzi** [Domattee/MIMo#20]
Hi there!

I've been playing around with controlling MIMo for a bit now, but I can't get gravity compensation to work as expected.

When I try to control the actuators with the external torques computed by MuJoCo in `qfrc_bias`, the arms shoot up. After some inspection, it appears as if the value computed for the `shoulder_ad_ab` is way larger than it should be.

Do you have any hints on what might be going on here? Am I messing something up when going form actuators to DOFs?

Thanks!

---
Here is a video of the behavior:
https://github.com/trieschlab/MIMo/assets/117986676/b610cfea-bc75-4851-bc7a-e8a666cce377

While here is an MRE:

```python

import os

import gymnasium as gym
import mimoEnv
from mimoEnv.envs.mimo_env import SCENE_DIRECTORY, DEFAULT_VISION_PARAMS
from mimoEnv.envs.dummy import MIMoDummyEnv
import mimoEnv.utils as env_utils

SELFBODY_XML = os.path.join(SCENE_DIRECTORY, "selfbody_scene.xml")

def main():
	env: MIMoDummyEnv = gym.make(
		"MIMoSelfBody-v0", model_path=SELFBODY_XML, 
		vision_params=DEFAULT_VISION_PARAMS, 
		proprio_params={'components': ['torque',]},
		render_mode="human")

	_ = env.reset()
	
	n_steps = 5000

	actuated_dofs = []

	for i in env.mimo_actuators:
		joint_id = env.model.actuator(i).trnid[0]
		actuated_dofs.append(env.model.joint(joint_id).dofadr[0])

	for _ in range(n_steps):

		ctrl = env.data.qfrc_bias[actuated_dofs]

		obs, reward, done, trunc, info = env.step(ctrl)
		
		env.render()
	

if __name__ == "__main__":
	main()
```

**Comment by Domattee** [comment]
Hi,

I've not worked with qfrc_bias before, but looking at the documentation I don't see why using it as the control input should lead to automatic gravity compensation. It seems to be a torque, probably in Nm, while the control inputs are unitless from 0 to 1. If qfrc_bias is the torque due to gravity (no guarantee that it is), you would at least have to consider the output torque of the actuator, "ctrl=qfrc_bias / actuator_gear" or similar.

**Comment by marcogfedozzi** [comment]
> Hi,
> 
> I've not worked with qfrc_bias before, but looking at the documentation I don't see why using it as the control input should lead to automatic gravity compensation. It seems to be a torque, probably in Nm, while the control inputs are unitless from 0 to 1. If qfrc_bias is the torque due to gravity (no guarantee that it is), you would at least have to consider the output torque of the actuator, "ctrl=qfrc_bias / actuator_gear" or similar.

Thank you for letting me realize I was forgetting the gear ratios!

As for the link between `ctrl` and `torque`, doesn't this function from the `SpringDamper` actuation model imply that the torque applied to each motor is just `ctrl * actuator_gear`?
https://github.com/trieschlab/MIMo/blob/9ca4a659f8e625d602266f903331b8dc0a6c8de4/mimoActuation/actuation.py#L180-L188 

As for my understanding, `qfrc_bias` holds the sum of Coriolis, centrifugal, and gravitational (generalized) force to which each joint is subjected. Hence, for a fully actuated system, setting the control equal to that would cancel it out, effectively compensating gravity (and the rest). E.g. see https://github.com/kevinzakka/mjctrl/blob/main/opspace.py.

**Comment by Domattee** [comment]
The torque mostly is ctrl*actuator_gear, but it doesn't account for the maximum torque limits (it should, I'll get on that). Control inputs are clamped to not exceed these when using the environment functions anyway, so there is no issue there, but if you set them manually you can exceed the limits and this function will be inaccurate. The simulation will use the limited torques, but the function will report the unlimited ones.

**Comment by marcogfedozzi** [comment]
Is there any reason for not using the values from `self.env.data.qfrc_actuator` to retrieve the torque generated on each joint?
It seems to account also for the `forcerange` limits, besides the `ctrlrange` ones.

**Comment by Domattee** [comment]
Yes, that is the value to get for the total actuator torque on each joint.

**Comment by Domattee** [comment]
Did you manage to get the gravity compensation working?

**Comment by marcogfedozzi** [comment]
Sorry for the late reply!

Yes, I can confirm that it was just a matter of keeping the gears into consideration, with something like

```python
ctrl = env.data.qfrc_bias[actuated_dofs] / env.model.actuator_gear[env.mimo_actuators, 0]
obs, reward, done, trunc, info = env.step(ctrl)
 ```

Everything looks fine :+1:
